<?php
include dirname(__FILE__) . '/../test_framework.php.inc';
include 'PEAR2/Pyrus/DirectedGraph.php';
include 'PEAR2/Exception.php';
include 'PEAR2/Pyrus/DirectedGraph/Exception.php';
include 'PEAR2/Pyrus/DirectedGraph/Vertex.php';
//include '/home/cellog/workspace/Pyrus/src/Pyrus/DirectedGraph.php';
//include '/home/cellog/workspace/PEAR2/Exception/trunk/src/Exception.php';
//include '/home/cellog/workspace/Pyrus/src/Pyrus/DirectedGraph/Exception.php';
//include '/home/cellog/workspace/Pyrus/src/Pyrus/DirectedGraph/Vertex.php';
$digraph = new PEAR2_Pyrus_DirectedGraph;
